Coloris/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import render
from django.conf.urls.static import static
from django.conf import settings


def home_view(request):
    print("Home view reached")
    return render(request, "home_template.html")


def about_view(request):

    return render(request, "about_template.html")


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", home_view, name="home_view"),
    path("home/", home_view, name="home_view"),
    path("about/", about_view, name="about_view"),
    path("game/", include("color_is.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

color_is/urls.py
from django.urls import path

from . import views
from django.conf.urls.static import static
from django.conf import settings

app_name = 'color_is'
urlpatterns = [
    path("play/", views.game_view, name="game_view"),
    path("evaluate_guess/", views.evaluate_guess_view, name="evaluate_guess_view"),
    path("final_score/", views.final_score_view, name="final_score_view"),
    path("score/", views.score_view, name="score_view"),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

color_is/models.py
from django.db import models

# Create your models here.

color_is/views.py
from django.shortcuts import render, redirect
import random

# Create your views here.


def game_view(request):
    # Initialize or get the score from the session
    score = request.session.get("score", 0)
    final_score = request.session.get("final_score", 0)

    # Logic to get a random color
    red = random.randint(0, 255)
    blue = random.randint(0, 255)
    green = random.randint(0, 255)

    # Set the current color in the session
    request.session['current_color'] = [red, green, blue]

    # Get round number
    round_number = request.session.get('round_number', 1)

    context = {
        "score": score,
        "current_color": (red, green, blue),
        "round_number": round_number,
        "final_score": final_score,
        "round_score": 0,
        "guessed_color": [0, 0, 0]
    }
    request.session.save()

    return render(request, 'game_template.html', context)


def evaluate_guess_view(request):
    if request.method == 'POST':
        # Get individual RGB components from the form data
        red = int(request.POST.get('red', 0))
        green = int(request.POST.get('green', 0))
        blue = int(request.POST.get('blue', 0))

        # Get the current color from the session if it exists
        current_color = request.session.get("current_color", [0, 0, 0])
        current_round = request.session.get('round_number', 1)
        current_score = request.session.get('score', 0)

        if current_round >= 5:
            final_score = current_score + 100
            final_score -= round((abs(red - current_color[0]) / 765) * 100, 0)
            final_score -= round((abs(green - current_color[1]) / 765) * 100, 0)
            final_score -= round((abs(blue - current_color[2]) / 765) * 100, 0)

            # Increment round number and update session info
            new_round = current_round + 1
            request.session['round_number'] = new_round

            request.session["final_score"] = final_score

            return redirect("color_is:score_view")
        else:
            # Logic to evaluate the user's guess and update the score
            new_score = current_score + 100
            new_score -= round((abs(red - current_color[0]) / 765) * 100, 0)
            new_score -= round((abs(green - current_color[1]) / 765) * 100, 0)
            new_score -= round((abs(blue - current_color[2]) / 765) * 100, 0)

            # Increment round number
            new_round = current_round + 1

        # Update the session with the new score and round number
        request.session['score'] = new_score
        request.session['round_number'] = new_round
        request.session["final_score"] = 0
        request.session["round_score"] = new_score - current_score
        request.session["guessed_color"] = [red, green, blue]

        request.session.save()
        return redirect("color_is:score_view")

    # Redirect to the next round or display the results
    request.session.save()
    return redirect('color_is:game_view')


def score_view(request):
    # Initialize or get the score from the session
    round_score = request.session.get("round_score", 0)
    current_color = request.session.get("current_color", [255, 255, 255])
    guessed_color = request.session.get("guessed_color", [255, 255, 255])
    round_number = request.session.get("round_number", 0)

    print(round_number)
    if round_number <= 5:
        context = {
            "round_score": round_score,
            "current_color": current_color,
            "guessed_color": guessed_color,
            "round_number": round_number,
            "link": "/game/play/"
        }
    elif round_number > 5:
        context = {
            "round_score": round_score,
            "current_color": current_color,
            "guessed_color": guessed_color,
            "round_number": round_number,
            "link": "/game/final_score/"
        }

        # Reset round and score values
        new_round = 1
        new_score = 0

        request.session['score'] = new_score
        request.session['round_number'] = new_round

    request.session.save()

    return render(request, 'score_template.html', context)


def final_score_view(request):
    # Initialize or get the score from the session
    final_score = request.session.get("final_score", 0)

    context = {
        "final_score": final_score
    }
    request.session.save()

    return render(request, 'final_score_template.html', context)

templates/about_template.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <link rel="shortcut icon" type="image/x-icon" href="{% static "favicon.ico" %}">
    <title>About Page</title>
</head>
<body>
    <div class="welcome_text" id="bobbingDiv">
        <span class="gradient-text">Coloris</span>
    </div>
    <nav class="navbar">
        <ul>
            <li><div class="navbar-text"><a href="/home/">Home</a></div></li>
            <li><div class="navbar-text"><a href="/game/play/">Play</a></div></li>
            <li><div class="navbar-text"><a href="/about/">About</a></div></li>
        </ul>
    </nav>
    <div class="about_text">
        <p>Coloris is a color identification game made by Luke Braun. The object of the game is to guess the RGB values
            that correspond to the color presented to the player. A score is calculated based on the player's guess. Compete
            against yourself and set a high score!</p>
        <p>&nbsp;</p>
        <p>Dedicated to and made for Lily :)</p>
    </div>
</body>

<script>
    // Get the div element
    var bobbingDiv = document.getElementById('bobbingDiv');

    // Set initial position
    var initialTop = 0;
    bobbingDiv.style.top = initialTop + 'px';

  // Set the bobbing motion
    function bob() {
        var amplitude = 10; // Adjust the bobbing height
        var speed = 1000; // Adjust the bobbing speed (milliseconds)

        // Calculate the new position using a sine wave for smooth bobbing
        var newPosition = initialTop + amplitude * Math.sin(Date.now() / speed);

        // Apply the new position to the top property
        bobbingDiv.style.top = newPosition + 'px';

        // Repeat the bobbing motion by using requestAnimationFrame
        requestAnimationFrame(bob);
    }

    // Start the bobbing motion
    bob();
</script>
<style>
    body {
        background-color: black;
    }

    .welcome_text {
        text-align: center;
        color: white;
        position: relative;
    }

    .gradient-text {
        background: linear-gradient(to right, red, orange, yellow, green, blue, indigo, violet);
        -webkit-background-clip: text; /* For WebKit browsers */
        color: transparent; /* Set text color to transparent */
        font-size: 6em;
        font-family: "Courier", serif;
        -webkit-text-size-adjust: none;
        font-weight: bold;
        -webkit-text-stroke-width: 1px;
        -webkit-text-stroke-color: white;
    }

    p, ul, li, label {
        font-family: "Courier", serif;
        -webkit-text-size-adjust: none;
        color: white;
    }

    h1, h2 {
        font-family: "Courier", serif;
        color: white;
    }

    .navbar {
        background-color: black;
        position: relative;
        z-index: 1000;
        width: 100%;
        box-sizing: border-box;
        margin-top: 20px;
        /* border: 3px solid;
        border-image: linear-gradient(to bottom right, red, orange, yellow, green, blue, indigo, violet) 1;
        border-radius: 15px; */
    }

    .navbar ul {
        list-style-type: none;
        margin: 0;
        padding: 0;
        background: black;
        display: flex;
        justify-content: center;
        align-items: center;
        border-radius: 15px;
    }

    .navbar li {
        display: inline-block;
        position: relative;
    }

    .navbar li:not(:first-child)::before {
        content: '';
        position: absolute;
        top: 50%;
        left: 0;
        transform: translateY(-50%);
        height: 70%;
        /* border-left: 3px solid;
        border-image: linear-gradient(to bottom right, red, orange, yellow, green, blue, indigo, violet) 1; */
    }

    .navbar li a {
        color: white;
        display: block;
        padding: 10px 30px;
        text-decoration: none;
    }

    .navbar-text {
        margin-left: 8px;
    }

    .navbar-text:hover {
        background-color: gray;
    }

    .about_text {
        margin: 50px 150px;
    }

    .about_text p {
        text-align: center;
    }
</style>
</html>

templates/final_score_template.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <link rel="shortcut icon" type="image/x-icon" href="{% static "favicon.ico" %}">
    <title>Final Score</title>
</head>
<body>
    <div class="final-score" id="bobbingDiv">
        <span class="gradient-text">Final Score: {{ final_score }}</span>
    </div>
    <nav class="navbar">
        <ul>
            <li><div class="navbar-text"><a href="/home/">Back to Home</a></div></li>
            <li><div class="navbar-text"><a href="/game/play/">Play Again</a></div></li>
        </ul>
    </nav>
</body>
<script>
    // Get the div element
    var bobbingDiv = document.getElementById('bobbingDiv');

    // Set initial position
    var initialTop = 0;
    bobbingDiv.style.top = initialTop + 'px';

    // Set the bobbing motion
    function bob() {
        var amplitude = 10; // Adjust the bobbing height
        var speed = 1000; // Adjust the bobbing speed (milliseconds)

        // Calculate the new position using a sine wave for smooth bobbing
        var newPosition = initialTop + amplitude * Math.sin(Date.now() / speed);

        // Apply the new position to the top property
        bobbingDiv.style.top = newPosition + 'px';

        // Repeat the bobbing motion by using requestAnimationFrame
        requestAnimationFrame(bob);
    }

    // Start the bobbing motion
    bob();
</script>
<style>
    body {
        background-color: black;
    }

    .final-score {
        text-align: center;
        color: white;
        position: relative;
        vertical-align: middle;
        margin-top: 20%;
    }

    .gradient-text {
        background: linear-gradient(to right, red, orange, yellow, green, blue, indigo, violet);
        -webkit-background-clip: text; /* For WebKit browsers */
        color: transparent; /* Set text color to transparent */
        font-size: 6em;
        font-family: "Courier", serif;
        -webkit-text-size-adjust: none;
        font-weight: bold;
        -webkit-text-stroke-width: 1px;
        -webkit-text-stroke-color: white;
    }

    p, ul, li, label {
        font-family: "Courier", serif;
        -webkit-text-size-adjust: none;
        color: white;
    }

    h1, h2 {
        font-family: "Courier", serif;
        color: white;
    }

    .navbar {
        background-color: black;
        position: relative;
        z-index: 1000;
        width: 100%;
        box-sizing: border-box;
        margin-top: 20px;
        /* border: 3px solid;
        border-image: linear-gradient(to bottom right, red, orange, yellow, green, blue, indigo, violet) 1;
        border-radius: 15px; */
    }

    .navbar ul {
        list-style-type: none;
        margin: 0;
        padding: 0;
        background: black;
        display: flex;
        justify-content: center;
        align-items: center;
        border-radius: 15px;
    }

    .navbar li {
        display: inline-block;
        position: relative;
    }

    .navbar li:not(:first-child)::before {
        content: '';
        position: absolute;
        top: 50%;
        left: 0;
        transform: translateY(-50%);
        height: 70%;
        /* border-left: 3px solid;
        border-image: linear-gradient(to bottom right, red, orange, yellow, green, blue, indigo, violet) 1; */
    }

    .navbar li a {
        color: white;
        display: block;
        padding: 10px 30px;
        text-decoration: none;
    }

    .navbar-text {
        margin-left: 8px;
    }

    .navbar-text:hover {
        background-color: gray;
    }

    form {
        display: inline-block;
    }
</style>
</html>

templates/game_template.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <link rel="shortcut icon" type="image/x-icon" href="{% static "favicon.ico" %}">
    <title>Game</title>
</head>
<body>
    <div class="welcome_text" id="bobbingDiv">
        <span class="gradient-text">Coloris</span>
    </div>
    <nav class="navbar">
        <ul>
            <li><div class="navbar-text"><a href="/home/">Home</a></div></li>
            <li><div class="navbar-text"><a href="/game/play/">Play</a></div></li>
            <li><div class="navbar-text"><a href="/about/">About</a></div></li>
        </ul>
    </nav>
    <div class="round-count"><h1>Round {{ request.session.round_number }}</h1></div>
    <div class="left-column">

    </div>
    <div class="middle-column">
        <div class="color-square" style="background-color: rgb({{ current_color.0 }}, {{ current_color.1 }}, {{ current_color.2 }}); width: 100px; height: 100px;"></div>
        <div class="sliders">
            <form method="post" action="{% url 'color_is:evaluate_guess_view' %}">
                {% csrf_token %}

                <div class="color-group">
                    <label for="red">Red:</label>
                    <input type="range" id="red" name="red" min="0" max="255" required>
                    <span id="redValue">122</span>
                </div>

                <div class="color-group">
                    <label for="green">Green:</label>
                    <input type="range" id="green" name="green" min="0" max="255" required>
                    <span id="greenValue">122</span>
                </div>

                <div class="color-group">
                    <label for="blue">Blue:</label>
                    <input type="range" id="blue" name="blue" min="0" max="255" required>
                    <span id="blueValue">122</span>
                </div>

                <button type="submit">Submit Guess</button>
            </form>
        </div>
    </div>
    <div class="right-column">

    </div>
    <div class="score">
        <p>Score: {{ score }}</p>
    </div>
</body>

<script>
    // Add event listeners to update the numerical values when sliders are moved
    document.getElementById('red').addEventListener('input', function() {
        document.getElementById('redValue').innerText = this.value;
    });

    document.getElementById('green').addEventListener('input', function() {
        document.getElementById('greenValue').innerText = this.value;
    });

    document.getElementById('blue').addEventListener('input', function() {
        document.getElementById('blueValue').innerText = this.value;
    });

    // Get the div element
    var bobbingDiv = document.getElementById('bobbingDiv');

    // Set initial position
    var initialTop = 0;
    bobbingDiv.style.top = initialTop + 'px';

    // Set the bobbing motion
    function bob() {
        var amplitude = 10; // Adjust the bobbing height
        var speed = 1000; // Adjust the bobbing speed (milliseconds)

        // Calculate the new position using a sine wave for smooth bobbing
        var newPosition = initialTop + amplitude * Math.sin(Date.now() / speed);

        // Apply the new position to the top property
        bobbingDiv.style.top = newPosition + 'px';

        // Repeat the bobbing motion by using requestAnimationFrame
        requestAnimationFrame(bob);
    }

    // Start the bobbing motion
    bob();
</script>
<style>
    body {
        background-color: black;
    }

    .welcome_text {
        text-align: center;
        color: white;
        position: relative;
    }

    .gradient-text {
        background: linear-gradient(to right, red, orange, yellow, green, blue, indigo, violet);
        -webkit-background-clip: text; /* For WebKit browsers */
        color: transparent; /* Set text color to transparent */
        font-size: 6em;
        font-family: "Courier", serif;
        -webkit-text-size-adjust: none;
        font-weight: bold;
        -webkit-text-stroke-width: 1px;
        -webkit-text-stroke-color: white;
    }

    p, ul, li, label {
        font-family: "Courier", serif;
        -webkit-text-size-adjust: none;
        color: white;
    }

    h1, h2 {
        font-family: "Courier", serif;
        color: white;
    }

    .navbar {
        background-color: black;
        position: relative;
        z-index: 1000;
        width: 100%;
        box-sizing: border-box;
        margin-top: 20px;
        /* border: 3px solid;
        border-image: linear-gradient(to bottom right, red, orange, yellow, green, blue, indigo, violet) 1;
        border-radius: 15px; */
    }

    .navbar ul {
        list-style-type: none;
        margin: 0;
        padding: 0;
        background: black;
        display: flex;
        justify-content: center;
        align-items: center;
        border-radius: 15px;
    }

    .navbar li {
        display: inline-block;
        position: relative;
    }

    .navbar li:not(:first-child)::before {
        content: '';
        position: absolute;
        top: 50%;
        left: 0;
        transform: translateY(-50%);
        height: 70%;
        /* border-left: 3px solid;
        border-image: linear-gradient(to bottom right, red, orange, yellow, green, blue, indigo, violet) 1; */
    }

    .navbar li a {
        color: white;
        display: block;
        padding: 10px 30px;
        text-decoration: none;
    }

    .navbar-text {
        margin-left: 8px;
    }

    .navbar-text:hover {
        background-color: gray;
    }

    .round-count {
        text-align: center;
    }

    .color-square {
        margin-left: auto;
        margin-right: auto;
    }

    .sliders {
        text-align: center;
        margin-top: 10px;
    }

    .color-group {
        display: flex;
        align-items: center;
        justify-content: center;
        margin-bottom: 10px;
    }

    label, input, span {
        margin-right: 10px;
    }

    form {
        display: inline-block;
    }

    #redValue, #greenValue, #blueValue {
        color: white;
        font-family: "Georgia", serif;
    }

    .score {
        text-align: center;
    }
</style>
</html>

templates/home_template.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <link rel="shortcut icon" type="image/x-icon" href="{% static "favicon.ico" %}">
    <title>Welcome Page</title>
</head>
<body>
    <div class="welcome-text" id="bobbingDiv">
        <span class="gradient-text">Coloris</span>
    </div>
    <nav class="navbar">
        <ul>
            <li><div class="navbar-text"><a href="/home/">Home</a></div></li>
            <li><div class="navbar-text"><a href="/game/play/">Play</a></div></li>
            <li><div class="navbar-text"><a href="/about/">About</a></div></li>
        </ul>
    </nav>
</body>

<script>
    // Get the div element
    var bobbingDiv = document.getElementById('bobbingDiv');

    // Set initial position
    var initialTop = 0;
    bobbingDiv.style.top = initialTop + 'px';

  // Set the bobbing motion
    function bob() {
        var amplitude = 20; // Adjust the bobbing height
        var speed = 1000; // Adjust the bobbing speed (milliseconds)

        // Calculate the new position using a sine wave for smooth bobbing
        var newPosition = initialTop + amplitude * Math.sin(Date.now() / speed);

        // Apply the new position to the top property
        bobbingDiv.style.top = newPosition + 'px';

        // Repeat the bobbing motion by using requestAnimationFrame
        requestAnimationFrame(bob);
    }

    // Start the bobbing motion
    bob();
</script>
<style>
    body {
        background-color: black;
    }

    .welcome-text {
        text-align: center;
        color: white;
        position: relative;
        vertical-align: middle;
        margin-top: 20%;
    }

    .gradient-text {
        background: linear-gradient(to right, red, orange, yellow, green, blue, indigo, violet);
        -webkit-background-clip: text; /* For WebKit browsers */
        color: transparent; /* Set text color to transparent */
        font-size: 10em;
        font-family: "Courier", serif;
        -webkit-text-size-adjust: none;
        font-weight: bold;
        -webkit-text-stroke-width: 1px;
        -webkit-text-stroke-color: white;
    }

    p, ul, li, label {
        font-family: "Courier", serif;
        -webkit-text-size-adjust: none;
        color: white;
    }

    h1, h2 {
        font-family: "Courier", serif;
        color: white;
    }

    .navbar {
        background-color: black;
        position: relative;
        z-index: 1000;
        width: 100%;
        box-sizing: border-box;
        margin-top: 20px;
        /* border: 3px solid;
        border-image: linear-gradient(to bottom right, red, orange, yellow, green, blue, indigo, violet) 1;
        border-radius: 15px; */
    }

    .navbar ul {
        list-style-type: none;
        margin: 0;
        padding: 0;
        background: black;
        display: flex;
        justify-content: center;
        align-items: center;
        border-radius: 15px;
    }

    .navbar li {
        display: inline-block;
        position: relative;
    }

    .navbar li:not(:first-child)::before {
        content: '';
        position: absolute;
        top: 50%;
        left: 0;
        transform: translateY(-50%);
        height: 70%;
        /* border-left: 3px solid;
        border-image: linear-gradient(to bottom right, red, orange, yellow, green, blue, indigo, violet) 1; */
    }

    .navbar li a {
        color: white;
        display: block;
        padding: 10px 30px;
        text-decoration: none;
    }

    .navbar-text {
        margin-left: 8px;
    }

    .navbar-text:hover {
        background-color: gray;
    }

    label, input, span {
        margin-right: 10px;
    }

    form {
        display: inline-block;
    }
</style>
</html>

templates/score_template.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <link rel="shortcut icon" type="image/x-icon" href="{% static "favicon.ico" %}">
    <title>Round Score</title>
</head>
<body>
    <div class="welcome-text" id="bobbingDiv">
        <span class="gradient-text">Coloris</span>
    </div>
    <p>The color is...</p>
    <p>({{ current_color.0 }}, {{ current_color.1 }}, {{ current_color.2 }})</p>
    <div class="color-square" style="background-color: rgb({{ current_color.0 }}, {{ current_color.1 }}, {{ current_color.2 }}); width: 100px; height: 100px;"></div>
    <p>You guessed...</p>
    <p>({{ guessed_color.0 }}, {{ guessed_color.1 }}, {{ guessed_color.2 }})</p>
    <div class="color-square" style="background-color: rgb({{ guessed_color.0 }}, {{ guessed_color.1 }}, {{ guessed_color.2 }}); width: 100px; height: 100px;"></div>
    <p>You scored {{ round_score }} points this round</p>
    <nav class="navbar">
        <ul>
            <li><div class="navbar-text"><a href={{ link }}>Continue</a></div></li>
        </ul>
    </nav>
</body>
<script>
    // Get the div element
    var bobbingDiv = document.getElementById('bobbingDiv');

    // Set initial position
    var initialTop = 0;
    bobbingDiv.style.top = initialTop + 'px';

    // Set the bobbing motion
    function bob() {
        var amplitude = 10; // Adjust the bobbing height
        var speed = 1000; // Adjust the bobbing speed (milliseconds)

        // Calculate the new position using a sine wave for smooth bobbing
        var newPosition = initialTop + amplitude * Math.sin(Date.now() / speed);

        // Apply the new position to the top property
        bobbingDiv.style.top = newPosition + 'px';

        // Repeat the bobbing motion by using requestAnimationFrame
        requestAnimationFrame(bob);
    }

    // Start the bobbing motion
    bob();
</script>
<style>
    body {
        background-color: black;
    }

    .welcome-text {
        text-align: center;
        color: white;
        position: relative;
    }

    .gradient-text {
        background: linear-gradient(to right, red, orange, yellow, green, blue, indigo, violet);
        -webkit-background-clip: text; /* For WebKit browsers */
        color: transparent; /* Set text color to transparent */
        font-size: 6em;
        font-family: "Courier", serif;
        -webkit-text-size-adjust: none;
        font-weight: bold;
        -webkit-text-stroke-width: 1px;
        -webkit-text-stroke-color: white;
    }

    .color-square {
        margin-left: auto;
        margin-right: auto;
    }

    p, ul, li, label {
        font-family: "Courier", serif;
        -webkit-text-size-adjust: none;
        color: white;
        text-align: center;
    }

    h1, h2 {
        font-family: "Courier", serif;
        color: white;
    }

    .navbar {
        background-color: black;
        position: relative;
        z-index: 1000;
        width: 100%;
        box-sizing: border-box;
        margin-top: 20px;
        /* border: 3px solid;
        border-image: linear-gradient(to bottom right, red, orange, yellow, green, blue, indigo, violet) 1;
        border-radius: 15px; */
    }

    .navbar ul {
        list-style-type: none;
        margin: 0;
        padding: 0;
        background: black;
        display: flex;
        justify-content: center;
        align-items: center;
        border-radius: 15px;
    }

    .navbar li {
        display: inline-block;
        position: relative;
    }

    .navbar li:not(:first-child)::before {
        content: '';
        position: absolute;
        top: 50%;
        left: 0;
        transform: translateY(-50%);
        height: 70%;
        /* border-left: 3px solid;
        border-image: linear-gradient(to bottom right, red, orange, yellow, green, blue, indigo, violet) 1; */
    }

    .navbar li a {
        color: white;
        display: block;
        padding: 10px 30px;
        text-decoration: none;
    }

    .navbar-text {
        margin-left: 8px;
    }

    .navbar-text:hover {
        background-color: gray;
    }

    form {
        display: inline-block;
    }
</style>
</html>